### PR TITLE
feat: renew fidelity bond

### LINKED ISSUE #610: feat: renew fidelity bond
> If "renew" is still a priority I'd say we create a new issue.

_Originally posted by @dergigi in https://github.com/joinmarket-webui/jam/issues/547#issuecomment-1422564749_

Feature: Provide an easy way for users to renew expired fidelity bonds. e.g. if a user wants to explicitly use the same UTXO for a new fidelity bond without an intermediary "unlock" operation.

**Describe the solution you'd like**
A concrete way to renew an expired FB without unfreezing it manually via the UI.
Prevent FBs from being unfrozen after they expire, but let it be used via distinct actions, -> See screenshots.

**Describe alternatives you've considered**
All alternatives that come to mind involve several manual steps by a user, which feels unnecessarily complicated.

**Additional context**

### PR DESCRIPTION
**Pull request by theborakompanioni**
Resolves #610 

Adds the ability to renew an expired fidelity bond.

This will be done with a direct-send creating a "single input, single output transaction" (this might not be what more advanced users want - e.g. CPFP is not possible afterwards). Feedback welcome.

In addition, the "Create FB" confirm dialog will now display the fee settings for the user to review before actually creating the bond.

## How to test

- Create an expired fidelity bond (only possible in dev mode with `npm run dev:start`)
- Renew expired fidelity bond (also, possibly with lockdate in the past)
- Rinse and repeat!

### CODE REVIEW

**Review by editwentyone — APPROVED** [review]

**Comment by theborakompanioni** [comment]
I am inclined to hide this behind a feature toggle till users can specify the tx fee directly when https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1360 is implemented. (There is a workaround by temporarily setting the txfee via `/configset` and resetting it to the previous value after the transaction.. but I think we do not want to go down this potentially error-prone  route..)

**Comment by theborakompanioni** [comment]
Revert to draft - blocked till https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1597 is tested and merged.

**Comment by editwentyone** [comment]
nice, one little thing: remove cancel button in this dialog

image

**Comment by theborakompanioni** [comment]
Unblocked. This can now be tackled once again.

**Comment by MarnixCroes** [comment]
nice, great work!

**Pull request merged**
