### PR TITLE
feat: add SchedulerConfirmationModal component for starting scheduled sweep

### LINKED ISSUE #796: (ui) Confirmation Modal before starting
subtask of #319 
Aim: To make a confirmation modal something like this.

image

Objective: Use the existing modal and create something with same design.

### PR DESCRIPTION
**Pull request by 0xSaksham**
This PR completes #796 

Made a Confirmation Modal that starts the scheduler only when the user confirms it.

image

### CODE REVIEW

**Review by editwentyone — CHANGES_REQUESTED** [review]
it would be nice to style this modal like the modals on "send" (jar selection, confirm, cancel)

- vertically centered
- different styling

**Comment by 0xSaksham** [comment]
> it would be nice to style this modal like the modals on "send" (jar selection, confirm, cancel)
> 
> * different styling

Let me know what you think of it in tomorrow's meeting. I would love some design help.

**Comment by 0xSaksham** [comment]
> * [x]  Make it vertically centered

image

Done, and also implemented design changes to make it look consistent.

**Review by editwentyone — APPROVED** [review]

**Comment by theborakompanioni** [comment]
Hey @0xSaksham - as discussed, would you be able to use `ConfirmModal` for that? I think we can save a lot of the custom stylings and reuse existing components (e.g. automatically have @editwentyone proposal to "vertically center" the content). Okay for you?

**Comment by 0xSaksham** [comment]
@theborakompanioni that works for me.

**Review by editwentyone — APPROVED** [review]

**Comment by 0xSaksham** [comment]
Hey @theborakompanioni , I personally feel that

This is okay!


<h3>but this looks better</h3>

**Comment by editwentyone** [comment]
@0xSaksham I can't see the pictures

**Comment by 0xSaksham** [comment]
> @0xSaksham I can't see the pictures

Is it visible now?

**Pull request merged**
