### PR TITLE
OrderBook added in footer

### LINKED ISSUE #752: drag Orderbook into Footer and/or Header
the order book is needed not only during earning but also sending and thus its maybe a better idea to have accessible all the time, it opens never the less as an overlay

### PR DESCRIPTION
**Pull request by SnehalSrivastava27**
Fixes #752.

### CODE REVIEW

**Comment by SnehalSrivastava27** [comment]
@theborakompanioni pull request added to add orderbook into footer

**Comment by theborakompanioni** [comment]
> @theborakompanioni pull request added to add orderbook into footer

Nice, @SnehalSrivastava27! I'll take a look asap! Thank you :pray:

**Comment by SnehalSrivastava27** [comment]
@theborakompanioni can you please tell why the build error is occurring I am unable to get it

**Comment by theborakompanioni** [comment]
> @theborakompanioni can you please tell why the build error is occurring I am unable to get it

The linter is failing. Could you rebase your changes on the latest `devel` branch and run `npm run format`? I think there was an update of `prettier`.

Also, could you:
- Make the new orderbook button the same styling as the "Cheatsheet"
- Label it "Orderbook" instead of "Show orderbook"

## :camera_flash: 

something similar to this



What do you think?

**Review by SnehalSrivastava27 — COMMENTED** [review]
Footer  can display  Orderbook

**Comment by SnehalSrivastava27** [comment]
There has been a issue in pushing the code I sincerely apologize for that along with that I am creating new PR please look into it

**Comment by SnehalSrivastava27** [comment]
image

**Comment by theborakompanioni** [comment]
> image

Made some small adaptions to align the styling of the nav links in the footer.
Thanks for your contribution @SnehalSrivastava27 ! Awesome : -)

**Review by theborakompanioni — APPROVED** [review]

**Comment by SnehalSrivastava27** [comment]
Thankyou so much for giving the chance to contribute

**Comment by theborakompanioni** [comment]
> Thankyou so much for giving the chance to contribute

Open source projects always appreciate any and all contributions!
Using the software, asking questions and reporting bugs is extremely important.
Code contributions are one of the best things that can happen to a small team. Thank you! :orange_heart:

**Pull request merged**
