### PR TITLE
chore: use `127.0.0.1` instead of `localhost` in setupProxy.js

### PR DESCRIPTION
**Pull request by theborakompanioni**
Users reported problems on [Raspibolt following this guide](https://raspibolt.org/guide/bonus/bitcoin/Jam.html).
See https://github.com/joinmarket-webui/jam/issues/608#issuecomment-1451831421
This seems to fix their problem while also having the development environment in functional state.

### CODE REVIEW

**Comment by kristapsk** [comment]
Concept ACK. I think the problem is that localhost defaults to IPv6 ::1, but processes might only listen to IPv4 127.0.0.1.

**Comment by theborakompanioni** [comment]
> Concept ACK. I think the problem is that localhost defaults to IPv6 ::1, but processes might only listen to IPv4 127.0.0.1.

Makes sense. Thanks for clarifying. :raised_hands: 
Sounds like the problem should rather be fixed in their setup, and "localhost" should be kept.

**Comment by kristapsk** [comment]
> "localhost" should be kept.

Don't see any benefits here. AFAIK you don't gain anything by using IPv6 for localhost over IPv4. Just using 127.0.0.1 everywhere makes things simpler and there will potentially be less problems. Only situation where this might not work is some hypothetical future machine where IPv4 support is abandoned in favour of IPv6.

**Review by openoms — APPROVED** [review]
utACK - makes sense

**Review by kristapsk — APPROVED** [review]
ACK 78f12007b8927e7ebeb7d67f537550ec2c0f6825 (tested by applying this patch on top of v0.1.5 on RaspiBolt)

**Pull request merged**
