### PR TITLE
Update SchedulerConfirmationModal.tsx

### PR DESCRIPTION
**Pull request by 0xSaksham**
minor production error

### CODE REVIEW

**Comment by 0xSaksham** [comment]
just had to change `showCloseButton` to `closeButton`. This PR fixes that!

**Comment by 0xSaksham** [comment]
This may break `devel` branch!!

**Comment by 0xSaksham** [comment]
I just merged the PR #796 and `devel` branch showed an error which was easy to fix.

But now it requires a review to merge this very small change!

**Review by barrytra — APPROVED** [review]
Yes, I was exactly stuck on this while reviewing a PR. This fixes the error :)

**Pull request merged**
