### PR TITLE
i18n: add Chinese translation :cn: (Simplified & Traditional)

### PR DESCRIPTION
**Pull request by Overload3910**
Imported the Chinese translations from Transifex that someone else did, because according to the matrix group, these are already finished. 

SCR-20230628-hcw

### CODE REVIEW

**Comment by theborakompanioni** [comment]
There are some build errors as the translation files are not imported correctly. Would you be able to make the necessary changes and verify that it works in your regtest environment?

If I can be of any service, please do not hesitate to ask! :pray:

**Comment by Overload3910** [comment]
Builds fine for me now. Can you confirm? :)

**Comment by theborakompanioni** [comment]
> Builds fine for me now. Can you confirm? :)

Yes. Looks great. :tada:

**Review by theborakompanioni — APPROVED** [review]
lgtm. I'd say we merge this now and wait for user feedback. :rocket

**Pull request merged**
