### PR TITLE
ui: add table pagination

### PR DESCRIPTION
**Pull request by theborakompanioni**
Adds pagination to the UTXO, Earn Report and Orderbook tables.

Before this PR, tables always display all entries.
When these changes are applied, tables will show 25 rows by default with options to switch to 25, 50, 100 rows respectively (or "Show All").

It is functional but can be improved from a UI perspective. All suggestions are very welcome.

### CODE REVIEW

**Comment by dnlggr** [comment]
Screenshot 2022-08-11 at 14 32 39

☝️ Small UI refresh to make it a bit lighter on the eye. What do you think? Diff below.

``` diff
diff --git a/src/components/TablePagination.tsx b/src/components/TablePagination.tsx
index 6ec6973..cf304b8 100644
--- a/src/components/TablePagination.tsx
+++ b/src/components/TablePagination.tsx
@@ -3,6 +3,8 @@ import { Pagination } from '@table-library/react-table-library/pagination'
 import * as TableTypes from '@table-library/react-table-library/types/table'
 import * as rb from 'react-bootstrap'
 import { useTranslation } from 'react-i18next'
+import Sprite from './Sprite'
+import styles from './TablePagination.module.css'
 
 const DEFAULT_PAGE_SIZES = [25, 50, 100]
 const DEFAULT_ALLOW_SHOW_ALL = true
@@ -24,11 +26,11 @@ export default function TablePagination({
 
   return (
     <div className="d-flex justify-content-between flex-column flex-md-row">
-      <div className="mt-3 mt-md-0 ms-3 ms-md-0 d-flex justify-content-center align-items-center order-2 order-md-1">
-        {t('global.table.pagination.items_per_page.label')}
+      <div className="mt-3 mt-md-0 ms-3 ms-md-0 d-flex justify-content-center align-items-center order-2 order-md-1 gap-2">
+        <div className="flex-shrink-0">{t('global.table.pagination.items_per_page.label')}</div>
         <rb.Form.Select
           aria-label={t('global.table.pagination.items_per_page.label')}
-          className="ms-2 d-inline-block w-auto"
+          className={styles.paginationSelect}
           defaultValue={pageSizes[0]}
           onChange={(e) => {
             const value = parseInt(e.target.value, 10)
@@ -47,26 +49,27 @@ export default function TablePagination({
         </rb.Form.Select>
       </div>
 
-      <div className="mt-3 mt-md-0 ms-3 ms-md-0 d-flex justify-content-center align-items-center order-1 order-md-2">
+      <div className="mt-3 mt-md-0 ms-3 ms-md-0 d-flex justify-content-center align-items-center order-1 order-md-2 gap-1">
         <rb.Button
           variant={'outline-dark'}
-          className="ms-1"
+          className={styles.paginationButton}
           disabled={pagination.state.page === 0}
           onClick={() => pagination.fns.onSetPage(0)}
         >
-          {t('global.table.pagination.page_selector.label_first')}
+          <Sprite symbol="caret-left" width="18" height="18" />
+          <Sprite symbol="caret-left" width="18" height="18" />
         </rb.Button>
         <rb.Button
           variant="outline-dark"
-          className="ms-1"
+          className={styles.paginationButton}
           disabled={pagination.state.page === 0}
           onClick={() => pagination.fns.onSetPage(pagination.state.page - 1)}
         >
-          {t('global.table.pagination.page_selector.label_previous')}
+          <Sprite symbol="caret-left" width="18" height="18" />
         </rb.Button>
         <rb.Form.Select
           aria-label={t('global.table.pagination.page_selector.label')}
-          className="ms-1 d-inline-block w-auto h-auto"
+          className={styles.paginationSelect}
           value={pagination.state.page}
           onChange={(e) => {
             const value = parseInt(e.target.value, 10)
@@ -82,19 +85,20 @@ export default function TablePagination({
         </rb.Form.Select>
         <rb.Button
           variant="outline-dark"
-          className="ms-1"
+          className={styles.paginationButton}
           disabled={pagination.state.page + 1 === pagination.state.getTotalPages(data.nodes)}
           onClick={() => pagination.fns.onSetPage(pagination.state.page + 1)}
         >
-          {t('global.table.pagination.page_selector.label_next')}
+          <Sprite symbol="caret-right" width="18" height="18" />
         </rb.Button>
         <rb.Button
           variant="outline-dark"
-          className="ms-1"
+          className={styles.paginationButton}
           disabled={pagination.state.page + 1 === pagination.state.getTotalPages(data.nodes)}
           onClick={() => pagination.fns.onSetPage(pagination.state.getTotalPages(data.nodes) - 1)}
         >
-          {t('global.table.pagination.page_selector.label_last')}
+          <Sprite symbol="caret-right" width="18" height="18" />
+          <Sprite symbol="caret-right" width="18" height="18" />
         </rb.Button>
       </div>
     </div>
diff --git a/src/i18n/locales/en/translation.json b/src/i18n/locales/en/translation.json
index d16f9ec..bc8ec8c 100644
--- a/src/i18n/locales/en/translation.json
+++ b/src/i18n/locales/en/translation.json
@@ -13,11 +13,7 @@
           "text_option_show_all": "All"
         },
         "page_selector": {
-          "label": "Page",
-          "label_first": "First",
-          "label_previous": "Previous",
-          "label_next": "Next",
-          "label_last": "Last"
+          "label": "Page"
         }
       }
     }
```

**Comment by theborakompanioni** [comment]
> point_up Small UI refresh to make it a bit lighter on the eye. What do you think? Diff below.

Love it! :heart_eyes:

**Comment by theborakompanioni** [comment]
Hope I managed to get the styles similar to yours. Thanks @dnlggr. :orange_heart: 

If you need a larger table to test the functionality, just execute e.g.  `./docker/regtest/mine-block.sh 126 <address>` and navigate to the utxo list.

**Comment by dergigi** [comment]
Nice! Looks good. 

Will have another look once conflicts are resolved @theborakompanioni

**Comment by theborakompanioni** [comment]
> Nice! Looks good.
> 
> Will have another look once conflicts are resolved @theborakompanioni

Conflicts resolved.

**Review by dergigi — APPROVED** [review]
tACK

Looks good to me ✅

**Pull request merged**
