### PR TITLE
(ui): Animated Cooking pot in dark and light mode

### PR DESCRIPTION
**Pull request by 0xSaksham**
Static Cooking Pot is done in dark and light mode.

### CODE REVIEW

**Comment by 0xSaksham** [comment]
@theborakompanioni cooking pot is animated now!

**Comment by 0xSaksham** [comment]
Check it out

https://www.loom.com/share/96138650f3b54b59b62584545875aa73?sid=2df0abe0-3797-442c-85dd-97cd8a6aa4fe

**Comment by 0xSaksham** [comment]
- [ ]  Make it look good in dark mode!

**Comment by 0xSaksham** [comment]
> * [x]   Make it look good in dark mode!

Done.

https://www.loom.com/share/deb64c767e23468db49c7df35ce6b248?sid=370c4323-c4fb-4973-bbd3-ff881b971f9f

**Comment by 0xSaksham** [comment]
This marks the completion of cooking pot-related tasks, I'll wait for @editwentyone  and @theborakompanioni code reviews and any new changes can be made in follow up PR's.

**Comment by 0xSaksham** [comment]
- [ ] Add Static Sprite as a Fallback

**Review by editwentyone — APPROVED** [review]
tACK, the animation is a bit hectic and I wouldn't fade the "soup" inside the pot. 

but to be fair, I also didn't add some input how to animate. so I am also glad, that you tackled the animation and made a first cut

**Comment by 0xSaksham** [comment]
> tACK, the animation is a bit hectic and I wouldn't fade the "soup" inside the pot.

I wanted to make it look like a wave, so I tried a lot of playing around with SVG's and animations. 
Not Promising, but I want to make it look like a wave. Does that sound good?

**Comment by 0xSaksham** [comment]
@editwentyone sorry for mentioning a lot. Should I merge these changes?

**Comment by editwentyone** [comment]
@0xSaksham could you deactivate the animation for this PR and open a new issue just for the animation please?

**Pull request closed without merging**
