### PR TITLE
ui: remove twitter link from settings page

### LINKED ISSUE #750: fix: remove twitter link
Twitter links are broken - replace with link to nostr or remove entirely.

### PR DESCRIPTION
**Pull request by 0xSaksham**
Resolves #750 

- [x] Removed Dead Twitter Link from Settings Page

### CODE REVIEW

**Comment by theborakompanioni** [comment]
Nice. Thanks @0xSaksham  :pray:

Can you also remove the `settings.jam_twitter` from the language files?

**Comment by 0xSaksham** [comment]
Sure man.

**Comment by 0xSaksham** [comment]
> Nice. Thanks @0xSaksham 🙏
> 
> Can you also remove the `settings.jam_twitter` from the language files?

Ready to Merge 👍

**Comment by theborakompanioni** [comment]
> > Nice. Thanks @0xSaksham 🙏
> > Can you also remove the `settings.jam_twitter` from the language files?
> 
> Ready to Merge 👍

Should it also be removed from the other language files?

**Comment by 0xSaksham** [comment]
I didn't know that. I'll do a full codebase search and remove it from everywhere.

**Comment by 0xSaksham** [comment]
Removed the Translation `"jam_twitter"` from files.

**Review by theborakompanioni — APPROVED** [review]

**Comment by 0xSaksham** [comment]
@theborakompanioni Should I `Squash and Merge` this into main branch?

**Pull request merged**
